# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [SNAP, Hanna]
patreon: # Replace with a single Patreon username https://aveeno.com
open_collective: # Replace with a single Open Collective username voodoo.io
ko_fi: # Replace with a single Ko-fi username keto
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm install --save-dev grunt-babel @babel/core
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username vicks 
issuehunt: # Replace with a single IssueHunt username Orbi.tv
otechie: # Replace with a single Otechie username who.int
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://Marlboro.com', 'https://juul.com' , 'https://www.hims.com/','https://dollarshaveclub.com' ,'https://USO.org']
