# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [KDMC, Hunter]
patreon: # Replace with a single Patreon username https://www.patreon.com/posts/22854182
open_collective: # Replace with a single Open Collective username voodoo.io
ko_fi: # Replace with a single Ko-fi username electron
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/wiki
community_bridge: # Replace with a single Community Bridge project-name e.g., slack-foundry
liberapay: # Replace with a single Liberapay username v8
issuehunt: # Replace with a single IssueHunt username AIU
otechie: # Replace with a single Otechie username fasta
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://Ibotta.com', 'https://harborfreight.com' , 'https://www.iheart.com/live/7620?cmp=ios_share&sc=ios_social_share&pr=false' 'https://dollarshaveclub.com' ,'https://rootbeer.com']
