nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs

# see package.json for Electron postinstall
enableScripts: false

# one week
npmMinimalAgeGate: 10080

npmPreapprovedPackages:
  - '@electron/*'
  - '@electron-forge/*'
  - 'electron'
