/** The built-in "Show Me" examples, with their display names, in menu order. No Electron or Node imports. */
export const SHOW_ME_EXAMPLES = [
  'App',
  'AutoUpdater',
  'BrowserView',
  'BrowserWindow',
  'Clipboard',
  'ContentTracing',
  'Cookies',
  'CrashReporter',
  'Debugger',
  'DesktopCapturer',
  'Dialog',
  'GlobalShortcut',
  'IPC',
  'Menu',
  'NativeImage',
  'Net',
  'Notification',
  'PowerMonitor',
  'PowerSaveBlocker',
  'Screen',
  'Session',
  'Shell',
  'SystemPreferences',
  'TouchBar',
  'Tray',
  'utilityProcess',
  'WebContents',
  'WebContentsView',
  'WebFrame',
] as const;

export type ShowMeExampleName = (typeof SHOW_ME_EXAMPLES)[number];
