#!/usr/bin/env node
// `yarn generate`: offline and idempotent code generation.
//
//   1. EIPC bindings: src/ipc/*.eipc -> src/ipc/generated/
//   2. i18n catalogs: src/i18n/locales/<locale>/<ns>.json -> src/i18n/generated/
//
// Generated source is committed. Files are only rewritten when their content
// changes, so running this while other tools watch the tree is cheap, and a
// clean checkout regenerates with no diff.
import { createHash } from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { generateWiring } from '@marshallofsound/ipc';

const appDir = path.resolve(import.meta.dirname, '..');
const HEADER =
  '// Generated by `yarn generate` (packages/app/tools/generate.mjs). Do not edit.\n';

async function listFiles(dir, prefix = '') {
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch (error) {
    if (error.code === 'ENOENT') return [];
    throw error;
  }
  const files = [];
  for (const entry of entries) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory())
      files.push(...(await listFiles(path.join(dir, entry.name), rel)));
    else files.push(rel);
  }
  return files;
}

/** Makes `dir` contain exactly `wanted` (relative path -> content). Returns the number of changes. */
async function syncDir(dir, wanted) {
  let changes = 0;
  for (const rel of await listFiles(dir)) {
    if (!wanted.has(rel)) {
      await fs.rm(path.join(dir, rel));
      changes++;
    }
  }
  for (const [rel, content] of wanted) {
    const file = path.join(dir, rel);
    const current = await fs.readFile(file, 'utf8').catch(() => undefined);
    if (current === content) continue;
    await fs.mkdir(path.dirname(file), { recursive: true });
    await fs.writeFile(file, content);
    changes++;
  }
  return changes;
}

// EIPC emits value-style imports of types (`import { AppState } from
// '../common/x.js'`), which `verbatimModuleSyntax` rejects and bundlers would
// keep. Everything in _internal/common is type-only, so mark those as types.
function fixTypeImports(rel, text) {
  if (!rel.startsWith('_internal/')) return text;
  text = text.replace(
    /^import \{([^}]*)\} from '(\.\.\/common\/[^']+)';$/gm,
    "import type {$1} from '$2';",
  );
  if (rel.startsWith('_internal/common/')) {
    text = text.replace(/^export \{ (\w+) \};$/gm, 'export type { $1 };');
  }
  return text;
}

// EIPC puts a random UUID in every channel name on each run. Replace it with
// one derived from the schemas, so output only changes when they do.
async function stableChannelId(schemaFolder) {
  const hash = createHash('sha256');
  for (const name of (await fs.readdir(schemaFolder))
    .filter((n) => n.endsWith('.eipc'))
    .sort()) {
    hash.update(name).update(await fs.readFile(path.join(schemaFolder, name)));
  }
  const hex = hash.digest('hex');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20, 32)}`;
}

async function generateIpc() {
  const schemaFolder = path.join(appDir, 'src/ipc');
  const outDir = path.join(schemaFolder, 'generated');
  const channelId = await stableChannelId(schemaFolder);
  const tmp = await fs.mkdtemp(path.join(os.tmpdir(), 'fiddle-eipc-'));
  // EIPC only writes into a folder that doesn't exist yet or that it created.
  const wiringFolder = path.join(tmp, 'out');
  try {
    await generateWiring({ schemaFolder, wiringFolder });
    const wanted = new Map();
    for (const rel of await listFiles(wiringFolder)) {
      let text = await fs.readFile(path.join(wiringFolder, rel), 'utf8');
      if (rel === '.eipc-generated') {
        // The original carries a timestamp, which would make every run a diff.
        text = 'Generated by EIPC through `yarn generate`. Do not edit files here.\n';
      } else if (rel.endsWith('.ts')) {
        text = fixTypeImports(rel, text).replace(
          /\$eipc_message\$_[0-9a-f-]{36}_\$_/g,
          `$eipc_message$_${channelId}_$_`,
        );
      }
      wanted.set(rel, text);
    }
    return await syncDir(outDir, wanted);
  } finally {
    await fs.rm(tmp, { recursive: true, force: true });
  }
}

async function readJson(file) {
  try {
    return JSON.parse(await fs.readFile(file, 'utf8'));
  } catch (error) {
    throw new Error(`${path.relative(appDir, file)}: ${error.message}`, { cause: error });
  }
}

// English is the source catalog: every key is `{ message, description,
// maxLength? }`. Other locales are plain i18next JSON v4 (`key: message`).
function compileMessages(locale, file, raw) {
  const where = path.relative(appDir, file);
  const messages = {};
  const problems = [];
  for (const [key, value] of Object.entries(raw)) {
    if (locale === 'en') {
      if (typeof value?.message !== 'string') problems.push(`${key}: missing "message"`);
      else if (typeof value.description !== 'string' || !value.description.trim()) {
        problems.push(`${key}: every key needs a "description"`);
      } else if (
        typeof value.maxLength === 'number' &&
        value.message.length > value.maxLength
      ) {
        problems.push(`${key}: longer than maxLength ${value.maxLength}`);
      } else messages[key] = value.message;
    } else if (typeof value === 'string') {
      messages[key] = value;
    } else {
      problems.push(`${key}: expected a string`);
    }
  }
  if (problems.length) throw new Error(`${where}:\n  ${problems.join('\n  ')}`);
  return messages;
}

async function compileI18n() {
  const localesDir = path.join(appDir, 'src/i18n/locales');
  const outDir = path.join(appDir, 'src/i18n/generated');
  const locales = (await fs.readdir(localesDir, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((a, b) => (a === 'en' ? -1 : b === 'en' ? 1 : a.localeCompare(b)));
  if (locales[0] !== 'en')
    throw new Error('src/i18n/locales/en is the source catalog and must exist');

  const namespacesOf = async (locale) =>
    (await fs.readdir(path.join(localesDir, locale)))
      .filter((name) => name.endsWith('.json'))
      .map((name) => name.slice(0, -'.json'.length))
      .sort();
  const namespaces = await namespacesOf('en');

  const wanted = new Map();
  const loaderLines = [];
  for (const locale of locales) {
    const entries = [];
    for (const ns of await namespacesOf(locale)) {
      if (!namespaces.includes(ns))
        throw new Error(`${locale}/${ns}.json has no English source`);
      const file = path.join(localesDir, locale, `${ns}.json`);
      const messages = compileMessages(locale, file, await readJson(file));
      wanted.set(
        `${locale}/${ns}.ts`,
        `${HEADER}export default ${JSON.stringify(messages, null, 2)} as const;\n`,
      );
      entries.push(`    ${JSON.stringify(ns)}: () => import('./${locale}/${ns}.js'),`);
    }
    loaderLines.push(`  ${JSON.stringify(locale)}: {\n${entries.join('\n')}\n  },`);
  }

  wanted.set(
    'index.ts',
    `${HEADER}
export const locales = ${JSON.stringify(locales)} as const;
export type Locale = (typeof locales)[number];

export const namespaces = ${JSON.stringify(namespaces)} as const;
export type Namespace = (typeof namespaces)[number];

export type Messages = Readonly<Record<string, string>>;
export type Loader = () => Promise<{ default: Messages }>;

/** One small module per locale and namespace, loaded on demand. */
export const loaders: Record<Locale, Partial<Record<Namespace, Loader>>> = {
${loaderLines.join('\n')}
};
`,
  );

  // Typed keys: t('main:newWindow') is checked against the English catalog.
  wanted.set(
    'i18next.d.ts',
    `${HEADER}${namespaces.map((ns) => `import type ${ns} from './en/${ns}';`).join('\n')}

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    keySeparator: false;
    resources: {
${namespaces.map((ns) => `      ${ns}: typeof ${ns};`).join('\n')}
    };
  }
}
`,
  );

  return await syncDir(outDir, wanted);
}

const [ipcChanges, i18nChanges] = await Promise.all([generateIpc(), compileI18n()]);
if (ipcChanges || i18nChanges) {
  console.log(`generate: ${ipcChanges} EIPC and ${i18nChanges} i18n file(s) updated`);
}
