name: Add to Ecosystem WG Project

on:
  issues:
    types:
      - opened
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - opened

permissions: {}

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        uses: electron/github-app-auth-action@e14e47722ed120360649d0789e25b9baece12725 # v2.0.0
        id: generate-token
        with:
          creds: ${{ secrets.ECOSYSTEM_ISSUE_TRIAGE_GH_APP_CREDS }}
          org: electron
      - name: Add to Project
        uses: dsanders11/project-actions/add-item@5767984408ccc6742f83acc8b8d8ea5e09f329af # v2.0.0
        with:
          field: Opened
          field-value: ${{ github.event.pull_request.created_at || github.event.issue.created_at }}
          project-number: 89
          token: ${{ steps.generate-token.outputs.token }}
